/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Propertius Global Design Tokens
        primary: '#081d50',
        'on-primary': '#ffffff',
        'primary-container': '#223366',
        'on-primary-container': '#8d9dd7',
        'inverse-primary': '#b5c4ff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b5c4ff',
        'on-primary-fixed': '#02174a',
        'on-primary-fixed-variant': '#344478',
        secondary: '#0058be',
        'on-secondary': '#ffffff',
        'secondary-container': '#2170e4',
        'on-secondary-container': '#fefcff',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        tertiary: '#000976',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1b2692',
        'on-tertiary-container': '#8c96ff',
        'tertiary-fixed': '#e0e0ff',
        'tertiary-fixed-dim': '#bdc2ff',
        'on-tertiary-fixed': '#000767',
        'on-tertiary-fixed-variant': '#2f3aa3',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#4c5c92',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464f',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#757680',
        'outline-variant': '#c5c6d1',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        // Semantic / status colors
        'status-high': '#ba1a1a',
        'status-medium': '#d97706',
        'status-low': '#059669',
        'ai-accent': '#7c3aed',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['28px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-tabular': ['14px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        gutter: '24px',
      },
      boxShadow: {
        card: '0px 4px 12px rgba(0,0,0,0.03)',
        modal: '0px 10px 25px rgba(34,51,102,0.08)',
        'ai-glow': '0 0 0 2px rgba(33,112,228,0.3)',
      },
      backgroundImage: {
        'ai-gradient': 'linear-gradient(135deg, #081d50, #2170e4)',
        'ai-border': 'linear-gradient(45deg, #2170e4, #adc6ff, #2170e4)',
      },
    },
  },
  plugins: [],
};
